name: Deploy

on:
  push:
    branches: [deployment/staging]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci 
      - run: npm run type
      - run: npm run build --if-present
  deploy:  
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Deploy Server
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.EMAIL}}
          heroku_app_name: authenticator
          branch: deployment/staging
          appdir: ./dist
      - name: Deploy Client       
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} 
          github-token: ${{ secrets.GITHUB }} 
          vercel-org-id: ${{ secrets.ORG_ID}}  
          vercel-project-id: ${{ secrets.PROJECT_ID}} 
          working-directory: ./public
        env: 
          HD_MONGODB_URL: ${{secrets.MONGODB_URL}}
          HD_GOOGLE_CLIENTID: ${{secrets.GOOGLE_CLIENTID}}
          HD_GOOGLE_SECRET: ${{secrets.GOOGLE_SECRET}}
          HD_SESSION_SECRET: ${{secrets.SESSION_SECRET}}

