name: Deploy app

on:
  push:
    branches: [deployment/staging]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Build
        run: |
          npm ci 
          npm run type
          npm run build --if-present

      - name: Login Heroku
        uses: AkhileshNS/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_email: ${{secrets.EMAIL}}
          justlogin: true
      - name: Deploy Server
        run: |
          git push https://git.heroku.com/${{secrets.HEROKU_APP_NAME_STAGING}}.git deployment/staging:master

      - name: Deploy Client
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GITHUB }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          working-directory: ./public
